name: CI
on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'apps/frontend/**'
      - 'apps/backend/**'
      - '.github/workflows/**'
  push:
    branches: [ dev ]
    paths:
      - 'apps/frontend/**'
      - 'apps/backend/**'
      - '.github/workflows/**'


jobs:
  frontend:
    # RUN only if there is a package.json in apps/frontend
    if: ${{ hashFiles('apps/frontend/package.json') != '' }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [22.19.0]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci || npm i
      - run: npm run lint --if-present
      - run: npm run build --if-present

  backend:
    # RUN only if one of the Java build files is present in apps/backend
    if: ${{ hashFiles('apps/backend/pom.xml') != '' || hashFiles('apps/backend/build.gradle') != '' || hashFiles('apps/backend/settings.gradle') != '' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
    steps:
      - uses: actions/checkout@v4
      - run: echo "backend placeholder"
